# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"
  config.vm.provision :shell, :path => "./bootstrap.sh"
  config.vm.network :forwarded_port, host: 4567, guest: 80
  #config.trigger.after :up, :execute => "./data/db_in.sh", :stdout => true
  #config.trigger.before :halt, :execute => "./data/db_out.sh", :stdout => true

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]

  #config.vm.provision :hosts do |provisioner|
    # Add a single hostname
    #provisioner.add_host 'dev-rds-01'

  #end
	
  #config.landrush.enabled = true
  #config.landrush.host 'dev-rds-01', '10.133.34.40'
end
